### ISSUE TITLE
refactor the code so non-devs can easily contribute aspects

### ISSUE THREAD

**Issue by robertpateii** [evangipson/faterator#5]
by "aspect" i mean any of the interesting data bits. One could say that "everything's an aspect" in FATE.

The problem I'd like to solve for is: As a tabletop person say I have a lot of good aspect ideas but no coding experience and I want to add them to the faterator without fear of breaking everything.

So one idea i mentioned on another Issue is to break them out into a 1 or more JSON files. Another idea would be running a database and server and building a form and sanitizing inputs (yuck). Another would be to just extend your module pattern some more so you have faterator.stunts and faterator.troubles which contain some logic plus their data. there probably other ideas too. 

I bring this up because you could very quickly end up in a situation where somebody adds 50 jobs and 50 aspects and 30 stunts per approach and now your brain file is huge.

And in addition to the metadata that's already been suggested for your aspects (id, approach), you'll probably be wanting more in the future (e.g. usually stunts relate to the high concept in some way).

given that you've done a good job of lumping the strings all together by their type already, I assume you were planning a step like this already. But it wasn't an issue so i'm adding it.

nice work!

**Comment by evangipson** [comment]
Taken care of as part of https://github.com/evangipson/faterator/pull/8!

brain.js and data.js are both around 500 lines now! yay!
