### ISSUE TITLE
i'd like a print out of my character to fit on one page and be black and white

### ISSUE THREAD

**Issue by robertpateii** [evangipson/faterator#7]
hey we talked about this and it's obvious but making an issue for it.

making it look like the default FAE would be cool, but at least one page and black and white to start.

**Comment by evangipson** [comment]
This was taken care of in https://github.com/evangipson/faterator/pull/8. Try and print to see the result!

If you'd like to suggest a more "complete" or "character sheety" version, I totally agree - you should create a new issue!
